lista_de_celebritati = {
    'Instagram': 346,
    'Cristiano Ronaldo': 215,
    'Ariana Grande': 183,
    'Dwayne Johnson': 181,
    'Selena Gomez': 174,
    'Kylie Jenner': 172,
    'Kim Kardashian': 167,
    'Lionel Messi': 149,
    'Beyoncé': 145,
    'Neymar': 138,
    'National Geographic': 135,
    'Justin Bieber': 133,
    'Taylor Swift': 131,
    'Kendall Jenner': 127,
    'Jennifer Lopez': 119,
    'Nicki Minaj': 113,
    'Nike': 109,
    'Khloé Kardashian': 108,
    'Miley Cyrus': 107,
    'Katy Perry': 94,
    'Kourtney Kardashian': 90,
    'Kevin Hart': 89,
    'Ellen DeGeneres': 87,
    'Real Madrid CF': 86,
    'FC Barcelona': 85,
    'Rihanna': 81,
    'Demi Lovato': 80,
    "Victoria's Secret": 69,
    'Zendaya': 68,
    'Shakira': 66,
    'Drake': 65,
    'Chris Brown': 64,
    'LeBron James': 63,
    'Vin Diesel': 62,
    'Cardi B': 67,
    'David Beckham': 82,
    'Billie Eilish': 61,
    'Justin Timberlake': 59,
    'UEFA Champions League': 58,
    'NASA': 56,
    'Emma Watson': 56,
    'Shawn Mendes': 57,
    'Virat Kohli': 55,
    'Gigi Hadid': 54,
    'Priyanka Chopra Jonas': 53,
    '9GAG': 52,
    'Ronaldinho': 51,
    'Maluma': 50,
    'Camila Cabello': 49,
    'NBA': 47
}
